# Generated by Django 5.2.3 on 2025-06-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings_city_listings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='listings',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='listings',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AddField(
            model_name='listings',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='listings',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('commercial', 'Коммерческая')], max_length=20, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AddField(
            model_name='listings',
            name='rooms',
            field=models.PositiveIntegerField(null=True, verbose_name='Комнат'),
        ),
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('sold', 'Продано')], default='active', max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='listings',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10, null=True, verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='listings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Агент'),
        ),
        migrations.AlterModelTable(
            name='listings',
            table=None,
        ),
    ]
